### ISSUE TITLE
MII PR Mikrobio Kultur Nachweis category

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#1]
Im Profil https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/StructureDefinition/kultur-nachweis stimmt etwas bei _Observation.category.coding:loinc-microbiology-studies_ mit dem Slicing/Pattern nicht. Es sind nur fixed Values auf _code_ und _display_ vorhanden. Es müsste wahrscheinlich dieser Code 18725-2 eine Ebene höher auf Coding definiert werden.

**Comment by rinaldie** [comment]
Danke, Code 18725-2 wurde eine Ebene höher  definiert

**Comment by rinaldie** [comment]
Es wurde mit pattern ersetzt
