### ISSUE TITLE
Missing binding in profile `MII_PR_Mikrobio_Kultur_Nachweis`

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#10]
The binding for `Observation.code` in the profile `MII_PR_Mikrobio_Kultur_Nachweis` does not feature a ValueSet url, only a description:

```json
{
  "id": "Observation.code",
  "path": "Observation.code",
  "label": "Kultur Nachweis",
  "patternCodeableConcept": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "11475-1"
      }
    ]
  },
  "mustSupport": true,
  "binding": {
    "strength": "required",
    "description": "Intensional Value Set Definition: LOINC {  {    STATUS in {ACTIVE}    CLASSTYPE in {1}    CLASS exclude {CHALSKIN, H&P.HX.LAB, H&P.HX, NR STATS, PATH.PROTOCOLS.*}  } }"
  }
}
```

**Comment by jpwiedekopf** [comment]
Feedback from Eugenia:

> Kultur Nachweis Observation.code ist kein Freitext sondern ein Pattern (LOINC 11475-1). Ich habe das Label entfernt, vielleicht war das die Ursache für die Verwirrung.

Ich habe kein Problem mit dem Pattern _as written_, aber dann ist doch kein Binding erforderlich? Sofern nur ein Code erlaubt ist, ist das Binding gänzlich redundant - das ganze `binding`-Element sollte entfernt sein, wenn ein fixed code gewünscht ist.

**Comment by rinaldie** [comment]
I changed the binding strength to "example" like in the case of molecular diagnostics . Do you think that is ok?

**Comment by jpwiedekopf** [comment]
Maybe I'm misunderstanding the intent, but the pattern disallows any other code other than `11475-1` this way? I think the code should be removed from `patternCoding`.

**Comment by alexzautke** [comment]
No, it doesn't. I just means that at least that code needs to be present. Additional codings can be chosen from the VS.

**Comment by alexzautke** [comment]
Only patterns defined on .coding prevents additional selection from the VS.

**Comment by jpwiedekopf** [comment]
Great, I learned a new thing today! Closing as resolved.
