### ISSUE TITLE
VS Serologischer_Test_Einheiten_UCUM includes UCUM codes with spaces

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#12]
The ValueSet `MII_VS_Mikrobio_Serologischer_Test_Einheiten_UCUM` includes a lot of UCUM issues that include spaces:

```json
[
    {
        "code": "IU / mL"
    },
    {
        "code": "[arb'U] / L"
    },
    {
        "code": "[arb'U] / mL"
    },
    {
        "code": "mg / L"
    },
    {
        "etc": "etc"
    }
]
```

The [UCUM specification states in *2.1 Character Set and Lexical Rules - §3 character set*](https://ucum.org/ucum#section-Character-Set-and-Lexical-Rules) that:

> White space is not recognized in a a [sic] unit term and should generally not occur. UCUM implementations may flag whitespace as an error rather than ignore it. Whitespace is not used as a separator of otherwise ambiguous parts of a unit term.

**Comment by jpwiedekopf** [comment]
This tangentially relates to #5: in the validation screenshot by @SevKohler, the #4 validation message states that `Code 'mg/l' does not exist in valueset 'https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/ValueSet/mii-vs-empfindlichkeit-einheiten-ucum'`.

UCUM has rather strict syntax rules for composing unit terms that aren't implemented by any kind of terminology server that I'm aware of. Hence, a lot of care must be taken creating UCUM ValueSets to ensure that the specification is precisely followed. In #5, the example resource has `valueQuantity.code` = `mg/l`, which is equivalent (in terms of physics/metrology) to the unit in the ValueSet `mg/L`, but that is not something a FHIR server or TS understands.

**Comment by rinaldie** [comment]
Thanks, the spaces were removed and the unit mg/l was changed to mg/L in the example
