### ISSUE TITLE
Wrong datatype in several profiles for fixed-code semantics

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#13]
In several profiles, the Observation.category.coding.code is fixed using `fixedCode`:

```json
{
  "id": "Observation.category.coding:loinc-microbiology-studies.code",
  "path": "Observation.category.coding.code",
  "min": 1,
  "fixedCode": "microbiology studies"
}
```

The `category` is of FHIR data type `CodeableConcept`, so using `"fixedCode": "microbiology studies"` is definitely wrong - this would be the display.

Instead, it should be sliced identically to the `Observation.code`:

```json
"patternCodeableConcept": {
  "coding": [
    {
      "system": "http://loinc.org",
      "code": " 18725-2"
    }
  ]
}
```

Note also the hint in the FHIR specification for [ElementDefinition](http://hl7.org/fhir/elementdefinition-definitions.html#ElementDefinition.fixed_x_):

> This is not recommended for Coding and CodeableConcept since these often have highly contextual properties such as version or display.

and the invariant `eld-24`:

> pattern[x] should be used rather than fixed[x]

It is certainly doable to use `fixedCoding` here, but this is not generally used within the CDS modules. Instead, `patternCodeableConcept` is generally used for fixed codes as shown above.

The following Observation profiles are affected:
- [x] [Kultur-Nachweis](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_kultur_nachweis)
- [x] [Empfindlichkeit](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_empfindlichkeit)
- [x] [Keimzahl](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_keimzahl)
- [x] [Mikroskopie](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_mikroskopie)
- [x] [Molekulardiagnostik](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_molekulare_diagnostik)
- [x] [MRE-Klasse](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_mre_klasse)
- [x] [MRGN-Klasse](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_mrgn_klasse)
- [x] [Resistenzgene](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_resistenzgene)
- [x] [Resistenzmutation](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_resistenzmutation)
- [x] [Serologie-Immunologie](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_serologie_immunologie)
- [x] [Virulenzfaktor](https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_virulenzfaktor)
- [x] [vorraussichtliche Empfindlichkeit](https://simplifier.net/Medizininformatik-Initiative-Modul-Mikrobiologie/MII_PR_Mikrobio_Voraussichtliche_Empfindlichkeit)

---
edit1: add invariant `eld-24`
edit2: Checklist

**Comment by rinaldie** [comment]
Thanks for the checklist, it really helped! it is done.
