### ISSUE TITLE
Narrative Div content is invalid

### ISSUE THREAD

**Issue by schwzr** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#18]
Some of the resources have invalid narrative div contents, that shall only contain valid xhtml (https://build.fhir.org/narrative.html#xhtml).

The narrative content is mostly correct (technically, I cannot make a statement about the content), except for some that are in the following format `...<h2>some title</tt>...`.

This means that it is no longer possible to load the resources in HAPI (and therefore also in IG Publisher, for example).

We have found the following resources in the microbiology package that have invalid narrative content:
- MII_VS_Mikrobio_Empfindlichkeit_Einheiten_UCUM [simplifier](https://simplifier.net/Medizininformatik-Initiative-Modul-Mikrobiologie/mii-vs-mikrobio-empfindlichkeit-einheiten-ucum/~overview)
- MII_VS_Mikrobio_Keimzahl_Einheiten_UCUM [simplifier](https://simplifier.net/Medizininformatik-Initiative-Modul-Mikrobiologie/mii-vs-mikrobio-keimzahl-einheiten-ucum/~overview)
- MII_VS_Mikrobio_Serologischer_Test_Einheiten_UCUM [simplifier](https://simplifier.net/Medizininformatik-Initiative-Modul-Mikrobiologie/mii-vs-mikrobio-serologischer-test-einheiten-ucum/~overview)

A fix exists by replacing `</tt>` in `</h2>` for the affected resources.

**Comment by patrick-werner** [comment]
Fixed on Simplifier
