### ISSUE TITLE
HTML-Fehler im mii-vs-mikrobio-empfindlichkeit-einheiten-ucum.json

### ISSUE THREAD

**Issue by haemka** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#20]
In der Datei mii-vs-mikrobio-empfindlichkeit-einheiten-ucum.json im aktuellen Package de.medizininformatikinitiative.kerndatensatz.mikrobiologie 2024.0.0 ist ein Fehler im HTML-Tag. Unserem FHIR-Server ist es so unmöglich das Paket zu parsen:
```
2024-10-17 14:20:25.069 [package_registry_validating.packageRegistryJettyServer-266] ERROR M:package_registry_validating R:YS3fxUQYjdgPXR7c c.c.a.w.JettyHealthCheckFilterHttpResponses - Failure during request processing
jakarta.servlet.ServletException: Request processing failed: ca.uhn.fhir.parser.DataFormatException: HAPI-1755: String does not appear to be valid XML/XHTML (error is "Unexpected close tag </tt>; expected </h2>.
 at [row,col {unknown-source}]: [1,86]"): <div xmlns="http://www.w3.org/1999/xhtml"><h2>MII VS Mikrobio Empfindlichkeit ucum</tt></div>
```

Das Package ist so nicht verwendbar.

**Comment by KutSaleh** [comment]
@alexzautke könntest du bitte drauf schauen? (siehe Issue #18 ebenfalls)

**Comment by alexzautke** [comment]
@patrick-werner Könntest du dich darum kümmern?

**Comment by patrick-werner** [comment]
fixed on simplifier

**Comment by KutSaleh** [comment]
Vielen Dank! Könntet ihr bitte ein neues Package (z. B. 2024.0.0-alpha1) bereitstellen? bzw. Wann ist geplant die nächste Release-Version (von 2024) zu veröffentlichen? 
Wir müssen das Package leider komplett neu installieren, um die Mibi-Daten auf dem FHIR-Server korrekt rein zu bekommen. Ohne diesen Bugfix können wir dies leider nicht.
