### ISSUE TITLE
MII PR Mikrobio Diagnostic Report category

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#4]
Bei `DiagnosticReport.category.coding:snomed-microbiology-studies` wäre es gut, den .display nicht im fixed value zu haben

**Comment by rinaldie** [comment]
Display wurde entfernt

**Comment by jpwiedekopf** [comment]
Siehe #13: hier sollte gemäß FHIR-Spec lieber `patternCoding` als `fixedCoding` verwendet werden.

**Comment by rinaldie** [comment]
Es wurde hier auch ein pattern hinzugefügt
