### ISSUE TITLE
Deprecated LOINC code in ValueSet Resistenz_Gene

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#6]
The LOINC code `48176-2|Deprecated Mycobacterium tuberculosis rifAMPin resistance (rpoB) gene [Presence] in Unspecified specimen by NAA with probe detection` is deprecated: https://loinc.org/48176-2/

A replacement code is offered: `89372-7|Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation [Presence] by Molecular method`, but not included in the ValueSet.

The deprecated code should be replaced by the replacement, rather than the deprecation being carried onwards, since the replacement code seems like a mapping that should hold for all instances of the deprecated code (all `48176-2` is-a `89372-7`) by definition.

**Comment by rinaldie** [comment]
Thanks. The depracted code was removed. 
The  replacement  code was not added as it was already included in the resistance mutation value set.
