### ISSUE TITLE
Wrong URL for SNOMED CT in several VS

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#7]
In several VS, the canonical URL for SNOMED CT is not correct. It SHOULD always be "http://snomed.info/sct":

|Filename|Name|wrong URL|
|-|-|-|
|`MII_VS_Mikrobio_Detection.json`|"MII_VS_Mikrobio_Qualitative_Labor_Ergebnisse_SNOMED"|`http://snomed.org`|
|`Morphologie.json`|"MII_VS_Mikrobio_Morphologie_SNOMEDCT"|`http://snomed.org`|
|`MII_VS_Mikrobio_voraussichtliche_Resistenz.json`|"MII_VS_Mikrobio_voraussichtliche_Empfindlichkeit_SNOMED"|`http://snomed.org`|
|`MRE.json`|"MII_VS_Mikrobio_MRE_Klasse_SNOMEDCT"|`http://snomed.org`|
|`Mikrskopie_methode.json`|"MII_VS_Mikrobiologie_Mikroskopiemethoden_SNOMEDCT"|`shttp://snomed.org`|

**Comment by jpwiedekopf** [comment]
No, sorry. The correct URL for SNOMED CT is `http://snomed.info/sct`, as per [the FHIR specification](https://terminology.hl7.org/SNOMEDCT.html#summary).

All ValueSets that use SNOMED CT, and profiles with patterns, need to be consistently changed. Please change the resources on Simplifier, and feel free to assign me so I can be your second set of eyes :)

**Comment by rinaldie** [comment]
That is funny... I think i had misunderstood the slide on TMF sharepoint and changed them all to http://snomed.org.

Oh well... they should all now be  http://snomed.info/sct

**Comment by jpwiedekopf** [comment]
Looks (almost) good to me! The only missing change seems to be in the IG (`guides/medizininformatikinitiative-modulmikrobio-implementationguide/IG-MII-Modul-Mikrobiologie/Technische-Implementierung/Terminologien.page.md` and `guides/medizininformatikinitiative-modulmikrobio-implementationguide/IG-MII-Modul-Mikrobiologie/Technische-Implementierung/Terminologien.page.md`), where `http://snomed.org` is still present.

**Comment by jpwiedekopf** [comment]
In `mii-vs-mikrobio-mikroskopiemethoden-snomedct.json`, there is still a `"system": "shttp://snomed.info/sct"` in line 55 (`rg "shttp"` in the terminal with the awesome [ripgrep](https://github.com/BurntSushi/ripgrep) tool).

**Comment by rinaldie** [comment]
Thanks, replaced!

**Comment by rinaldie** [comment]
> Looks (almost) good to me! The only missing change seems to be in the IG (`guides/medizininformatikinitiative-modulmikrobio-implementationguide/IG-MII-Modul-Mikrobiologie/Technische-Implementierung/Terminologien.page.md` and `guides/medizininformatikinitiative-modulmikrobio-implementationguide/IG-MII-Modul-Mikrobiologie/Technische-Implementierung/Terminologien.page.md`), where `http://snomed.org` is still present.

thanks, this should also have been fixed both in DE and EN
