### ISSUE TITLE
ValueSet "MII_VS_Mikrobio_Morphologie_SNOMEDCT" includes all SNOMED CT

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#8]
The ValueSet "MII_VS_Mikrobio_Morphologie_SNOMEDCT" (canonical: `https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/ValueSet/mii-vs-mikrobio-morphologie-snomedct`) includes all of SNOMED CT:

```json
"compose": {
    "include": [
      {
        "system": "http://snomed.info/sct"
      },
      {
        "concept": [
          {
            "code": "723529006",
            "display": "Extracellular Gram-negative diplococcus (finding)"
          },
          { 
            "concept": ["more explicit codes"],
            "system": "http://snomed.org"
          }
       ]
    }
  ]
}
```

This is likely not intended. Note also the wrong SCT url, as stated in #7 .

**Comment by rinaldie** [comment]
Thanks, the VS was restricted to the intended 8 values. . The URL  for SNOMED was replaced with http://snomed.org .
