### ISSUE TITLE
Probably incorrect URL in CLSI

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-mikrobiologie#9]
The ValueSet `CLSI` (canonical `https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/ValueSet/mii-vs-mikrobio-clsi-hl7`) references a CodeSystem with URL `http://terminology.hl7.org/ImplementationGuide/hl7.terminology` in the `compose.include`.

This URL does not resolve to anything, and if it did, it would likely reference the entire IG from HL7, rather than a CodeSystem.

**Comment by rinaldie** [comment]
Thanks for noticing. The URL was replaced with "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation". This should solve the issue
